### ISSUE TITLE
Step fails without explicitly defining environment variables

### ISSUE THREAD

**Issue by vmax** [wercker/step-pip-install#5]
Before I explicitly set `WERCKER_PIP_INSTALL_PIP_COMMAND=pip` and `WERCKER_PIP_INSTALL_REQUIREMENTS_FILE=requirements.txt` in Environment, build was failing with error:

(without pip and req.txt)
```
No virtual environment detected. Sudo will be used for pip install
Running pip install with sudo: sudo  install  
install: missing file operand
Try 'install --help' for more information.
failed: pip install failed
```

(with pip and without req.txt)
```
No virtual environment detected. Sudo will be used for pip install
Running pip install with sudo: sudo pip install  
You must give at least one requirement to install (see "pip help install")
pip install succeeded
```

**Comment by gsserge** [comment]
Thanks for the reporting. The issue is identified and being worked on. In the meantime, the step has been rolled back to the latest working version.
